### PR TITLE
Linq query not working

### PR DESCRIPTION
**Pull request by bleissem**
Hello @JonPSmith ,

we found an Exception when reading nested values from nested dto's.
We also tried to use the PerDtoConfig class to avoid the error but still the error occurs.
To demonstrate that behaviour to you, we just modified the test TestInDtosNestedOk
and added 
TestInDtosNestedOk2
with a linq query that shows the exception

IList<InContactAddressDto> resp = service.ReadManyNoTracked<InContactAddressDto>().Where(x => x.Addess.Address1 == "some street").ToList();

Can you please look at the exception ? Thanks in advance.

System.InvalidOperationException : The LINQ expression 'Where<ContactAddress>(
    source: DbSet<ContactAddress>, 
    predicate: (c) => new InContactAddressDto{ Name = c.Name }
    .Addess.Address1 == "some street")' could not be translated

### CODE REVIEW

**Comment by JonPSmith** [comment]
HI @bleissem,

I think you have a error in your unit test. On line 82 you test `contact` rather that `resp`. Can you check that.

**Comment by bleissem** [comment]
Hi @JonPSmith ,
yes we do test the contact query.
The assignment 
IList<InContactAddressDto> resp =
is something that can be omitted

**Comment by JonPSmith** [comment]
I think is a simple typo error in your unit test. The problem is that you load the `contact` using a direct EF call ```context.ContactAddresses.SingleOrDefault();``` to check the `CreateAndSave` worked. But you then check it for the `Address` part, which you didn't load.

Try changing the last line to 
```c#
resp.Single().Address.Address1.ShouldEqual("some street"); 
```

**Comment by JonPSmith** [comment]
If that isn't it then send me the stack trace with the line it fails on.

**Comment by florianraffl** [comment]
Hi @JonPSmith,

thanks for your response! I fixed the wrong test code in our branch but the problem is that the error already occures on line 80 because the query which your generic services made are to complex and linq can't make these as SQL queries, which is new in .netcore 3.0 where linq throws an exception if linq can't be converted to SQL. 
The question is now why is that simple where clause causing such a complex query where linq can't convert it. 

The stacktrace is here:
QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
    QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
    Database.CompileQuery[TResult](Expression query, Boolean async)
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
    <>c__DisplayClass9_0`1.<Execute>b__0()
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    QueryCompiler.Execute[TResult](Expression query)
    EntityQueryProvider.Execute[TResult](Expression expression)
    EntityQueryable`1.GetEnumerator()
    List`1.ctor(IEnumerable`1 collection)
    Enumerable.ToList[TSource](IEnumerable`1 source)

Looking forward to your response!

Best Regards,
Florian Raffl

**Comment by JonPSmith** [comment]
Glad GenericServices is correct. 

Yes, EF Core 3 is a bit change and has some big consequences. I suggest you hand-code the query and play around to see what does/doesn't work. 

Do let me know what you find.

**Comment by florianraffl** [comment]
Yea if you use only properties of top DTO class in your where expression than everything works great.  Unfortunately if you use nested DTOs in a where clause like:
`service.ReadManyNoTracked().Where(x => x.Addess.Address1 == "some street").ToList();`
this LINQ error occures. 
It looks like the auto generated LINQ expression from GenericServices to map DTO to DB-Object is way to complex for ef core 3.0 but I don't know how these things are done in GenericServices so it might be helpful if you could help us out.
I think the generic services might be adjusted for using ef core 3.0.

You can easily reproduce this behaviour if you use a property of a nested DTO in a where clause as shown above. This seems to be a general problem and it doesn't only happen on this example in this pull request.

**Comment by JonPSmith** [comment]
I have loads of nested DTO queries in my unit tests and they all work OK. That's why I was so sure your test had to be wrong.

You need to hand-code the query and check it,

**Comment by florianraffl** [comment]
I can't find any tests in your Tests project where you use nested DTO queries.
Can you give us an example of this?

**Comment by florianraffl** [comment]
I added a new commit where you can see that if I use DB Object directly in GenericServices everything works fine. (`TestInDtosNestedOk2` Row 54) 
But if i use DTOs over GenericServices (`TestInDtosNestedOk3` Row 90) runtime exception was thrown at where clause.

**Comment by florianraffl** [comment]
Hi @JonPSmith,

because we got no answer from here we found another repository for this problem. So i will close this pull request now.

**Pull request closed without merging**
